### ISSUE TITLE
register package or take it?

### ISSUE THREAD

**Issue by Roger-luo** [Roger-luo/PlutoCLI.jl#2]
Hi @fonsp do you want me to register this package or do you want to just copy the code to Pluto directly (since this is a very small package...) either would work.

the v0.3 version of Comonicon can now generates shell completions in ZSH, which I think will make things easier in terminal when Pluto expose more functionality on the CLI side. (or maybe there is some other function I could forward command line to?)

**Comment by fonsp** [comment]
Hey! I'm thinking to create a package PlutoUtils.jl that contains this(!), online deployment methods, conversion to other notebook formats, and more. What do you think?

**Comment by Roger-luo** [comment]
that sounds great! I could make a PR to that package later then.

**Comment by Roger-luo** [comment]
ok we are moving this back now.
